from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.8.0")


##### setup report #####
configfile: "config/config.yaml"


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/fusion.smk"
include: "rules/diffexp.smk"
include: "rules/tpm.smk"
include: "rules/enrich.smk"
include: "rules/rmats.smk"
include: "rules/xCell.smk"
include: "rules/venn.smk"
##### target rules #####


rule all:
    input:
        get_final_output(),
        expand("results/enrichment/{contrast}",contrast=config["diffexp"]["contrasts"]),
        expand("results/rmats/{contrast}",contrast=config["diffexp"]["contrasts"]),
        expand("results/Fusion/{unit}/{sample}/star-fusion.fusion_predictions.tsv",sample=samples["sample_name"],unit=units["unit_name"]),
        expand("results/Fusion/{unit}/{sample}/star-fusion.fusion_predictions.abridged.tsv",sample=samples["sample_name"],unit=units["unit_name"]),