log <- file(snakemake@log[[1]], open = "wt")
sink(log)
sink(log, type="message")
library(xCell)
exprMatrix = read.table(snakemake@input[[1]],header=TRUE,row.names=1, as.is=TRUE)

data=xCellAnalysis(exprMatrix)
out_dir=dirname(snakemake@output[[1]])
write.table(data,file=file.path(out_dir,"xCell.csv"))
library(pheatmap)
png(file.path(out_dir,"xCell.png"),height=800,width=480)
pheatmap(data,cluster_rows = F,cluster_cols = F)
dev.off()
